FROM imachug/kyzylborda_lib
RUN apk add --no-cache gcc musl-dev linux-headers
RUN pip install gunicorn
WORKDIR /app
COPY web/requirements.txt ./
RUN pip install -r requirements.txt
COPY web ./
CMD ./start.sh
