category:  reverse
points:    150
title:     PEBCAK
author:    ivanq
description: >
    <p>
        Программист Вася администрирует компьютеры в Большой Фирме. Программировать Вася умеет, а
        администрировать &mdash; не очень, поэтому проблемы безопасности он решает, храня свой
        пароль администратора в зашифрованном виде.
    </p>
    <p>
        Вы очень хотите поставить себе пасьянс, но гадкий Вася его отключил, поэтому теперь вам
        очень хочется достать Васин пароль. К счастью, после десяти минут расхваливания Васиных
        способностей вы упросили его поделиться кодом шифрования пароля, а из логов справились
        достать зашифрованный пароль. А вот что с ним делать дальше, уже не очень понятно.
    </p>
generator: ../_scripts/kyzylborda-lib-generator
attachments_path: attachments
secrets:
    seed: DnlJAIchbniwMdktdi0w9EluDcki1hv2
    flag: ugra_thats_not_how_access_control_works_[0-9a-z]{12}
