category: web
title:    "Сельский блог"
points:   100
author:   nsychev
description: |
    <p>К сожалению, Сельский клуб закрылся, не продержавшись на вершине медиабизнеса даже трёх месяцев. А вот местная Сельская служба новостей пережила временное падение рейтингов и снова вышла на стабильный показатель в 14 читателей.</p>
    <p>Однако, теперь перед изданием встала проблема гораздо  серьёзнее — глобальная рецессия. А это отток рекламодателей и, как следствие, серьёзных финансовых потоков.</p>
    <p>С целью сохранения редакции было принято беспрецедентное решение — введение платной подписки на тексты издания. Беспрецедентно оно тем, что качество текстов ни на йоту не повысилось. Как и информационная безопасность веб-сайта издания.</p>
# todo: generator, daemon
secrets:
  seed: "FMUEg>$9&){/ULZ46Ye)eZ#KxeQ1E?yW"
  flag: "ugra_please_dont_read_it_you_didnt_pay_[a-z0-9]{12}"
generator: ../_scripts/kyzylborda-lib-generator
daemon:
  exec: kyzylborda-docker-compose-daemon
  cwd: app
  socket: ./app.sock
  socket_type: http
