category: ppc
points: 400
title: Советские вступительные в ясельный класс
author: gudn
description: >
  <p>Васе скоро надо будет сдавать ВЯК, и за день до экзамена он решил подготовиться.

  <p>Сейчас он на задании про написание рекурсивных функций. К сожалению, доступ к компьютеру у Васи есть только в школе, и тот... мягко говоря, не первой свежести — лет ему примерно столько же, сколько и понятию рекурсии в программировании.

  <p>Но деваться некуда. Экзамен на носу. У вас есть ключи от кабинета информатики, можете сами поиграться с этой железякой. Поможете Васе?

  <p><em>Обновлено 14 января в 18:00:</em> Исправлена опечатка в задаче.
attachments_path: attachments
generator: ../_scripts/kyzylborda-lib-generator
daemon:
  exec: kyzylborda-docker-compose-daemon
  cwd: app
  socket: ./qrec.sock
  socket_type: 'http'
secrets:
  seed: VSQid3EH2ToeiR0HEe+PcSWV85UH+6r9
  flag: ugra_ugra_ugra_ugrec_[a-z0-9]{12}
